FROM {{image}}
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y wget sudo

RUN useradd -m -s /bin/bash -u {{uid}} -U {{username}} \
    && echo "{{username}}:{{password}}" | chpasswd

RUN if [ -z "$(which rstudio-server)" ]; then \
        apt install -y gdebi-core \
        && . /etc/os-release \
        && wget https://download2.rstudio.org/server/${VERSION_CODENAME}/amd64/rstudio-server-2023.12.1-402-amd64.deb \
        && gdebi -n rstudio-server-2023.12.1-402-amd64.deb; \
    else \
        echo "RStudio Server is already installed."; \
    fi

RUN echo "" >> $(Rscript -e 'cat(R.home())')/etc/Renviron.site \
  && cat /etc/environment >> $(Rscript -e 'cat(R.home())')/etc/Renviron.site

RUN echo '{{username}} ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/{{username}} \
 && echo "auth-required-user-group={{username}}" >> /etc/rstudio/rserver.conf \
 && echo "#!/bin/bash" > /home/{{username}}/entrypoint.sh \
 && echo "sudo service rstudio-server start" >> /home/{{username}}/entrypoint.sh \
 && echo "echo 'Server running with the following credentials:'" >> /home/{{username}}/entrypoint.sh \
 && echo "echo 'Username: {{username}}'" >> /home/{{username}}/entrypoint.sh \
 && echo "echo 'Password: {{password}}'" >> /home/{{username}}/entrypoint.sh \
 && echo "echo 'Access at http://127.0.0.1:{{port}} to use RStudio Server.'" >> /home/{{username}}/entrypoint.sh \ && echo "sleep infinity" >> /home/{{username}}/entrypoint.sh \
 && chmod +x /home/{{username}}/entrypoint.sh

EXPOSE {{port}}

ENTRYPOINT ["/home/{{username}}/entrypoint.sh"]
CMD []
